basePath: /
definitions:
  database.Behavior:
    properties:
      avgLoginInterval30d:
        format: float64
        type: number
      burstinessLoginInterval:
        format: float64
        type: number
      cstDimID:
        format: int64
        type: integer
      ewmLoginInterval7d:
        format: float64
        type: number
      fanoFactorLoginInterval:
        format: float64
        type: number
      freqChange7dVsMean:
        format: float64
        type: number
      lastOsCategorical:
        type: string
      lastPhoneModelCategorical:
        type: string
      loginFrequency7d:
        format: float64
        type: number
      logins7dOver30dRatio:
        format: float64
        type: number
      loginsLast7Days:
        format: int64
        type: integer
      loginsLast30Days:
        format: int64
        type: integer
      monthlyOsChanges:
        format: int64
        type: integer
      monthlyPhoneModelChanges:
        format: int64
        type: integer
      stdLoginInterval30d:
        format: float64
        type: number
      transdate:
        type: string
      varLoginInterval30d:
        format: float64
        type: number
      zscoreAvgLoginInterval7d:
        format: float64
        type: number
    type: object
  views.ClassificationResult:
    properties:
      probability_of_fraud:
        type: number
    type: object
  views.Client:
    properties:
      cst_dim_id:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
    type: object
  views.ClientDetailed:
    properties:
      behaviors:
        items:
          $ref: '#/definitions/database.Behavior'
        type: array
      cst_dim_id:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      transactions:
        items:
          $ref: '#/definitions/views.Transaction'
        type: array
    type: object
  views.ErrorResponse:
    properties:
      error:
        example: validation_error
        type: string
      message:
        example: Phone number already registered
        type: string
    type: object
  views.SignInCodeRequest:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  views.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  views.TokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  views.Transaction:
    properties:
      amount:
        type: integer
      destination:
        type: string
      full_name_of_sender:
        type: string
      target:
        type: integer
      transdatetime:
        type: string
    type: object
  views.TransactionData:
    properties:
      amount:
        type: integer
      avg_login_interval_30d:
        type: number
      burstiness_login_interval:
        type: number
      ewm_login_interval_7d:
        type: number
      fano_factor_login_interval:
        type: number
      flogins_7d_over_30d_ratio:
        type: number
      freq_change_7d_vs_mean:
        type: number
      last_os_categorical:
        type: string
      last_phone_model_categorical:
        type: string
      login_frequency_7d:
        type: number
      logins_last_7_days:
        type: number
      logins_last_30_days:
        type: number
      monthly_os_changes:
        type: integer
      monthly_phone_model_changes:
        type: integer
      std_login_interval_30d:
        type: number
      transdate:
        type: string
      var_login_interval_30d:
        type: number
      zscore_avg_login_interval_7d:
        type: number
    type: object
  views.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
host: ai-hackathon-2025-api.onrender.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server AI-HACKATHON.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AI HACKATHON 2025
  version: "1.0"
paths:
  /v1/auth:
    patch:
      consumes:
      - application/json
      parameters:
      - description: LogIn data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.SignInCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.TokensResponse'
        "404":
          description: Invalid Data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "409":
          description: Conflict of Code
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't find the user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Login to get the code and compare
      tags:
      - Auth
    post:
      consumes:
      - application/json
      parameters:
      - description: LogIn data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.TokensResponse'
        "400":
          description: Invalid Data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: wrong passwors
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not Present
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "425":
          description: Too Often
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't query
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Login to send the code to phone
      tags:
      - Auth
  /v1/clients:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/views.Client'
            type: array
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User profile
      tags:
      - Clients
  /v1/clients/{cst_dim_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: cst_dim_id
        in: path
        name: cst_dim_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ClientDetailed'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User profile
      tags:
      - Clients
  /v1/profile:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.User'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User profile
      tags:
      - Users
  /v1/transactions:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/views.Transaction'
            type: array
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User profile
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.TransactionData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ClassificationResult'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get Result
      tags:
      - Transactions
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
